---
db:
  adapter: sqlite
  config:
    dsn: ./my_flora.sqlite
devices: []
miflora:
  poller:
    adapter: bluepy
plants: []
stats:
  statsd:
    use: true
    config:
      host: localhost
      port: 8125
      prefix: myflorametrics
  prometheus:
    use: true
