---
plants: []
devices: []
stats:
  statsd:
    use: true
    config:
      host: localhost
      port: 8125
      prefix: myflorametrics
  prometheus:
    use: true
db:
  adapter: sqlite
  config:
    database: ./my_flora.sqlite
device_poller:
  adapter: 'bluepy'
