---
plants:
  - species: 'Camellia Japonica'
    tag: 'Camellia_Japonica'
    moisture: [15, 60]
    fertility: [350, 2000]
    sunlight: [2000, 25000]
    temperature: [6, 25]
devices:
  - address: 'C4:7C:8D:6B:C0:0E'
    label: 'Camelia 1'
    tag: 'Camellia_Japonica'
